[Feat/#3] DiaryFeed Empty UI
2024memozi/android pull request #14
Opened 2024-09-01 07:59 UTC by SYAAINN

## 📌 PR 요약

🌱 작업한 내용
- 기본 ui 구현
- 리스트 <-> 캘린더 선택 기능 구현
- 일기 작성 버튼 클릭 시 작성 카드 구현
- 일기 피드 디스플레이 카드 구현

🌱 PR 포인트
[미구현 요소]

- [ ] 메모/설정 네비게이션 연결
- [ ] 캘린더 클릭 시 캘린더 바텀시트 
- [ ] 일기 작성 시 글자수 카운트 기능
- [ ] 일기 작성 시 카메라/갤러리 접근
- [ ] 일기 작성 시 위치 작성 다이얼로그
- [ ] 일기 작성 시 랜덤 기능

## 📸 스크린샷
|스크린샷|
|:--:|
|파일첨부바람|

https://github.com/user-attachments/assets/7582e078-9600-4d4b-8950-a232487674f5

## 📮 관련 이슈
- Resolved: #3

2024-09-01 14:39 UTC, hyoeunjoo reviewed
역시 ㅋ 컴포즈로 한 번 앱잼 해본 사람은 뚝딱 빠르게 만드네요
아직 컴포즈 뉴비라 사실 코드리뷰도 틀린게 많을거라고 생각합니다...^^ 같이 토론하면서 성장해여

2024-09-01 14:39 UTC, hyoeunjoo commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/DiaryFeedScreen.kt
> +    MemoziBackGround()
보니까 해당 BackGround부분은 제 뷰에서도 사용하고 있네요
해당 함수를 재사용하기 위해 기본값은 원래대로 두되, 나중에 원하는 값만큼 변경해서 사용할 수 있게 함수를 약간 고쳐봤습니다. 맞는지는 모르겠는데 한 번 봐주세요 ㅎㅎ

```
@Composable
fun MemoziBackGround(
    topWeight: Float = 17f, 
    bottomWeight: Float = 50f 
) {
    Column(
        modifier = Modifier.fillMaxSize()
    ) {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .weight(topWeight)
                .background(
                    brush = MemoziTheme.colors.gradientBrush
                )
        )
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .weight(bottomWeight) 
                .background(
                    color = MemoziTheme.colors.white
                )
        )
    }
}

```
이렇게 하면 나중에 다른곳에서 해당 화면이 필요할때도 재사용 할 수 있을것같아요
혼잣말 겸.. 같이 봐주세요 겸..

2024-09-01 14:39 UTC, hyoeunjoo commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DiaryFeedTopAppBar.kt
> +}
음~ 이렇게 함수 만들어놓고 가져와서 쓰는거군용

2024-09-01 14:39 UTC, hyoeunjoo commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/DiaryFeedScreen.kt
> +            )
피그마랑 비교해보니까 현재 이 중간 구분선이 양옆 아이콘의 중앙에 위치해야 할 것 같아요
지금은 row의 top에 딱 붙어있네요
`                Modifier.align(Alignment.CenterVertically)
`
요거 추가해주시면 더 예쁘게 나올 것 같아요!

2024-09-01 14:39 UTC, hyoeunjoo commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DiaryFeedGreeting.kt
> +            color = MemoziTheme.colors.white,
이런것처럼 자주쓰거나 불변인 text들 string 추출하면 좋을 것 같아요

2024-09-01 14:39 UTC, hyoeunjoo commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DiaryFeedWriteCard.kt
> +                            )
round가 8dp인 보라색 버튼이 많아 보이네요 이 부분은 재사용 할 수 있게 따로 빼는게 좋을 것 같아요

@Composable
```
fun Custom8dpPurpleButton(  // 네이밍 그지같음 이슈..^^;
    text: String,
    onClick: () -> Unit,
    enabled: Boolean = true
) {
    Button(
        onClick = onClick,
        modifier = Modifier
            .width(68.dp)
            .height(34.dp)
            .align(Alignment.CenterVertically),
        enabled = enabled,
        shape = RoundedCornerShape(8.dp),
        colors = ButtonDefaults.buttonColors(
            contentColor = MemoziTheme.colors.white,
            containerColor = MemoziTheme.colors.mainPurple
        ),
        contentPadding = PaddingValues(horizontal = 22.dp, vertical = 6.dp)
    ) {
        Text(
            text = text,
            modifier = Modifier.padding(0.dp),
            style = MemoziTheme.typography.ssuLight12
        )
    }
}
```

뭐 대충 이런 식으로.. 할 수 있으려나요..?

2024-09-01 14:39 UTC, hyoeunjoo commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DiaryFeedWriteCard.kt
> +                            enabled = isDiaryAvailable,
이 부분은 하드코딩 되어 보입니다 이렇게 되면 기기대응이 되지 않는다고 알고 있어요!
xml에서는 layout_constraintDimensionRatio로 비율코딩을 했는데 찾아보니 compose에서는 Modifier.aspectRatio(비율값)등으로 사용하는 것 같더라구요 이 부분 한 번 확인해주시면 감사하겠습니다 ㅎ_ㅎ

2024-09-02 06:22 UTC, SYAAINN reviewed
컴포즈 처음이라면서 리뷰 보고 놀랐습니다.. 성장 속도가 기대가 되네요

2024-09-02 06:22 UTC, SYAAINN commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/DiaryFeedScreen.kt
> +    MemoziBackGround()
너무 잘고쳐서 벙쪘습니다.. 바로 반영하겠습니다

2024-09-02 06:22 UTC, SYAAINN commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/DiaryFeedScreen.kt
> +            )
깜빡했는데 감사합니다!

2024-09-02 06:22 UTC, SYAAINN commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DiaryFeedGreeting.kt
> +            color = MemoziTheme.colors.white,
현재 서버로부터 받아와야 할 값들, 하드코딩 되어야하는 것들이 혼재되어 있어서 나중에 서버 붙이면서 추출하도록 하겠습니다!

2024-09-02 06:22 UTC, SYAAINN commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DiaryFeedWriteCard.kt
> +                            enabled = isDiaryAvailable,
맞습니다 ,, 컴포즈를 사용하다보면 컴포넌트들이 기본적으로 가지고 있는 Padding 값으로 인해 원하는 모양을 구현하기가 (커스텀하기가) 굉장히 까다로운 부분이 몇 개 있는데요, 버튼이 개인적으로 그 중 하나입니다! 현재는 ui구현이 우선이라 하드코딩 해놨지만 추후 수정토록 하겠습니다!

2024-09-02 06:22 UTC, SYAAINN commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DiaryFeedWriteCard.kt
> +                            )
피그마를 보니 버튼의 색상도 다양해서 파라미터로 뺄 부분을 좀 더 살펴보면 좋을 것 같습니다! 앱 전체에서 재사용 할 수 있을만한 버튼 컴포넌트를 한번 만들어보도록 하겠습니다!

2024-09-02 06:34 UTC, cacaocoffee requested changes
수고하셨어요! 며칠안에 이렇게 빨리 뷰를 짜시다니 대단하시네요 
gitignore 설정과 memoziTopappbar를 제대로 못짜 재활용 하지못하게 된거 같아 죄송한 느낌이 드네요 ㅠㅜ

2024-09-02 06:34 UTC, cacaocoffee commented on .idea/vcs.xml
.idea에 해당하는 코드들은 빌드 과정 속에서 생겨난 파일이라 깃허브에 올리진않아도 될거 같습니다. 
각각의 역할은 
https://duzi077.tistory.com/276 

git ignore 에 추가하는 방법입니다.
https://velog.io/@bybye527/Git-.gitignore-%EC%9D%B4%EB%9E%80-feat.idea

ignore 세팅을 제가 잘 못해서 생긴일 같네요

2024-09-02 06:34 UTC, cacaocoffee commented on feature/diaryfeed/build.gradle.kts
주석 처리 되어 있는 부분 삭제해도 될거 같습니다.

2024-09-02 06:34 UTC, cacaocoffee commented on feature/diaryfeed/proguard-rules.pro
proguard-rule 과 consumer-rule 또한 마찬가지로 없애도 될거같아요

2024-09-02 06:34 UTC, cacaocoffee commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/DiaryFeedScreen.kt
> +    MemoziBackGround()
좋은 생각 같아요 인자로 비율 줘서 하는게 좀 더 범용성 있게 쓸거같네요!

2024-09-02 06:34 UTC, cacaocoffee commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/DiaryFeedScreen.kt
> +    var isDiaryExist by remember { mutableStateOf(true) }
추후 이부분은 viewmodel 로 빼면 될거 같아요!

2024-09-02 06:34 UTC, cacaocoffee commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DiaryFeedGreeting.kt
> +            color = MemoziTheme.colors.white,
username 은 파라미터로 받아서 넣는게 좋을 거 같아요 
추후에 viewmodel을 통해 연결했을때 값을 넘겨서 처리하게 되는데 인자로 받는게 바꾸기도 편하구요!

2024-09-02 06:34 UTC, cacaocoffee commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DailyDiaryItem.kt
이미지, 위치가 없을 때에 대한 뷰도 처리할 필요가 있어보여요 
nullable인자로 받아서 null일 때 처리하면 될거 같아요!

2024-09-02 06:34 UTC, cacaocoffee commented on settings.gradle.kts
오 아주 좋네요! 야무지다... 분리까지

2024-09-02 06:34 UTC, cacaocoffee commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DiaryFeedWriteCard.kt
> +                        )
이부분 반복되는 부분이 많아서 함수로 분리하면 좋을거 같아요

2024-09-02 06:37 UTC, cacaocoffee commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DiaryFeedWriteCard.kt
> +                            enabled = isDiaryAvailable,
가장 큰부분을 화면에 대한 비율을 계산하고 fillmaxWidth(0.~f) . aspectRatio(0.5f) 이런식으로 변경하면 기기대응에 맞게 할 수 있을거 같아요 저도 엄청 큰애들은 이렇게 하는데 자잘한 애들은 좀 어렵더라구요..

2024-09-02 07:33 UTC, SYAAINN commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DailyDiaryItem.kt
네 좀 더 구체적으로 컴포넌트화 하도록 하겠습니다!

2024-09-02 07:33 UTC, SYAAINN commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DiaryFeedGreeting.kt
> +            color = MemoziTheme.colors.white,
맞습니다..! 반영하겠습니다!

2024-09-02 12:16 UTC, cacaocoffee approved these changes
수고하셨어요!

2024-09-02 12:58 UTC, SYAAINN commented on feature/diaryfeed/src/main/java/com/memozi/diaryfeed/component/DiaryFeedWriteCard.kt
> +                            enabled = isDiaryAvailable,
컴포넌트를 제작하기엔 길어질 것 같아 추후 반영토록 하겠습니다!

2024-09-02 12:58 UTC, merged