#13 memo search detail
2024memozi/android pull request #20
Opened 2024-09-08 03:26 UTC by hyoeunjoo

## 📌 PR 요약

🌱 작업한 내용
- 메모 검색 화면, 메모 상세 화면 ui 작업했습니다

🌱 PR 포인트
-

## 📸 스크린샷
|스크린샷|

- 메모 검색화면

https://github.com/user-attachments/assets/f885f2ff-8b11-448e-8a3f-81358423f3a5

-메모 입력 화면

https://github.com/user-attachments/assets/87e3ec16-9edd-46c5-8952-bb26f17e126d

## 📮 관련 이슈
- Resolved: #13

+ 일단 작업이 많이 늦어진 점 죄송하다는 말씀 드립니다. 아직 제대로된 ui는 아닙니다ㅠㅠ 피그마랑 다른 부분이 많습니다. 일단 pr올리고 대략적인 뷰 구성 방식에 대한 코드리뷰를 받고 싶습니다. 언제나.. 환영입니다 절 혼내주세요.

해당 pr올리고 또 바로 작업하겠습니다! 이젠 디테일적인 요소들을 좀 잡고 기능 추가해보겠습니다!

2024-09-08 15:20 UTC, cacaocoffee requested changes
수고하셨어요! 고생 많이 한게 느껴지네요 코멘트 열심히 달아보았답니다. 
열심히 한게 느껴져서 더욱 열심히! 달았어요 
.idea 로 시작하는 파일들의 경우는 안올리는게 좋답니다. .gitignore에 *.idea를 추가하면 돼요! 
(제가 먼저 잘했뒀어야하는데 죄송할따름이네요)

항상 하시다가 모르는 거나 어렵거나 궁금하다! 싶은 거 있으면 편하게 연락주세요!

2024-09-08 15:20 UTC, cacaocoffee commented on feature/memo/src/main/java/com/memozi/memo/MemoDetailScreen.kt
> +    var memoValue by remember { mutableStateOf("") }
추후 viewmodel로 분리 해서 사용하면 좋을거같아요

2024-09-08 15:20 UTC, cacaocoffee commented on feature/memo/src/main/java/com/memozi/memo/MemoDetailScreen.kt
> +fun MemoDetailScreen() {
메모 디테일 스크린이 너무 많은 정보를 가지고 있는 것같아요 
예를들면 Textfield와 같은 부분은 함수로 분리해서 보면 각각 화면에 맞게 비교해서 보기 편하지 않을까 싶네요

2024-09-08 15:20 UTC, cacaocoffee commented on feature/memo/src/main/java/com/memozi/memo/MemoSearchScreen.kt
> +                horizontalArrangement = Arrangement.SpaceBetween,
이런 정렬 적극적으로 사용하시는거 좋은거 같아요!

2024-09-08 15:20 UTC, cacaocoffee commented on feature/memo/src/main/java/com/memozi/memo/MemoSearchScreen.kt
> +                    Spacer(modifier = Modifier.width(8.dp))
```suggestion
               Text(
                text = "|",
                style = MemoziTheme.typography.ngReg15,
                color = MemoziTheme.colors.gray07,
            )
            Spacer(modifier = Modifier.width(4.dp))
```
이렇게 바꾸면 피그마 디자인에 좀 더 맞는 디자인이 될거같아요

2024-09-08 15:20 UTC, cacaocoffee commented on feature/memo/src/main/java/com/memozi/memo/MemoSearchScreen.kt
> +                        text = "카테고리에서 ${memoItems.size}개의 메모를 발견했습니다!",
완벽해...!

2024-09-08 15:20 UTC, cacaocoffee commented on feature/memo/src/main/java/com/memozi/memo/MemoSearchScreen.kt
> +fun memoSearchList(dummyData: List<Pair<String, List<MemoItem>>>) {
dummyData라는 이름은 모의값을 넣는것이라는 의미를 담는거 같아요 
SearchList나Category~ 이런식으로 추후 함수 호출을 통해 넘어오는 값을 좀 더 잘 식별할 수 있는 이름으로 매개변수의 이름을 짓는게 좋아보여요

2024-09-08 15:20 UTC, cacaocoffee commented on feature/memo/src/main/java/com/memozi/memo/MemoDetailScreen.kt
> +                Divider(
혹시 Divider를 쓰신 이유를 알 수 있을까요?

2024-09-08 15:20 UTC, cacaocoffee commented on feature/memo/src/main/java/com/memozi/memo/MemoSearchScreen.kt
> +fun MemoSearchScreen() {
이친구가 맨 위로 올라가는게 좋을거 같아요 파일 이름이 MemoSearhScreen인 만큼 이친구를 먼저 통해서 읽구 점차 밑에서 
위에 있는 여러 함수들을 통해 UI 를 파악하기 좋을거 같아서요

2024-09-08 15:20 UTC, cacaocoffee commented on feature/memo/src/main/java/com/memozi/memo/MemoSearchScreen.kt
> +    MemoziBackground(topWeight = 10f, bottomWeight = 48f)
현재 MemoziBackground(topWeight = 10f, bottomWeight = 48f) 를 통해 경계선을 나누었으나 
각각의 값은 고정적인 dp 값을 통해 조절하는 걸로 보여요 이런 경우엔 디바이스에 따라 원하지 않는 결과물이 나올 수 있답니다
<img width="388" alt="image" src="https://github.com/user-attachments/assets/2ec09978-289a-4611-997c-285c8e2dfecb">
 
 이건 하나의 예시예요  투두리스트와 위의 간격이 뭔가 좁은 느낌이 들거나 
 
<img width="385" alt="image" src="https://github.com/user-attachments/assets/4ffbedfd-a83b-4e49-b6d7-9d32f0dab718">

아예 간격이 부족해 질 수 도 있답니다.

2024-09-08 15:20 UTC, cacaocoffee commented on feature/memo/src/main/java/com/memozi/memo/MemoDetailScreen.kt
> +    var memoValue by remember { mutableStateOf("") }
이건 나중에 천천히!

2024-09-09 04:57 UTC, hyoeunjoo commented on feature/memo/src/main/java/com/memozi/memo/MemoDetailScreen.kt
> +    var memoValue by remember { mutableStateOf("") }
넵!

2024-09-09 04:58 UTC, hyoeunjoo commented on feature/memo/src/main/java/com/memozi/memo/MemoSearchScreen.kt
> +fun memoSearchList(dummyData: List<Pair<String, List<MemoItem>>>) {
넵 알겠습니다!

2024-09-09 04:58 UTC, hyoeunjoo commented on feature/memo/src/main/java/com/memozi/memo/MemoDetailScreen.kt
> +                Divider(
구분 선이 하나 있더라구요 1dp짜리.. 그래서 divider로  넣어줬습니다

2024-09-09 04:59 UTC, hyoeunjoo commented on feature/memo/src/main/java/com/memozi/memo/MemoSearchScreen.kt
> +fun MemoSearchScreen() {
그렇겠네요 감사합니다

2024-09-09 04:59 UTC, hyoeunjoo commented on feature/memo/src/main/java/com/memozi/memo/MemoSearchScreen.kt
> +    MemoziBackground(topWeight = 10f, bottomWeight = 48f)
저도 하면서.. 이건 아닌 것 같다는 생각을 했습니다. 좀 더 나은 방법을 생각해볼게요!

2024-09-10 04:08 UTC, cacaocoffee commented on feature/memo/src/main/java/com/memozi/memo/MemoSearchScreen.kt
> +    MemoziBackground(topWeight = 10f, bottomWeight = 48f)
Column(){
  Box(modifier.weight(10)){
   검색 창부분
  }
  Box(modifier.weight(46?)){
     투두리스트 부분
  }
}

이런식으로 할 수 있을거 같아요!

2024-09-14 03:27 UTC, cacaocoffee approved these changes
수고하셨어요 바쁜 와중에 잠쪼개가면서 ㅠㅜㅠㅜ
좋은 팀원 만나서 감사합니다

2024-09-14 03:27 UTC, merged